name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: charge .env
        run: cd s8 && cp .env.example .env
        
      - name: Start stack
        run: cd s8 && docker compose up -d
      
      - name: run migrations 

        run: cd s8 && npx knex migrate:latest --knexfile knexfile.ts
      - name: run seeds
        run: cd s8 && npx knex seed:run --knexfile knexfile.ts

      - name: Run tests
        run: cd s8 && npm run test /test/*.spec.ts

      - name: Stop
        if: always()
        run: cd s8 && docker compose down -v