name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: charge .env
        run: cd s8 && cp .env.example .env

      - name: Start stack
        run: cd s8 && docker compose up -d

      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: s8/package-lock.json

  
      - name: Instalar dependencias
        working-directory: s8
        run: npm ci

      - name: Run tests
        run: cd s8 && npm run test 

      - name: Stop
        if: always()
        run: cd s8 && docker compose down -v