name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug paths
        run: |
          pwd
          ls -la
          ls -la s8 || true

      - name: Node & cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: s8/package-lock.json

      - name: Copiar .env
        working-directory: s8
        run: cp .env.example .env
      - name: Levantar Postgres (volumen nombrado)
        working-directory: s8
        run: docker compose up -d db

      - name: Instalar deps (limpia permisos si es necesario)
        run: |
          sudo rm -rf s8/node_modules || true
          cd s8 && npm ci

      - name: Tests
        working-directory: s8
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          CI: true
        run: npm run test

      - name: Down
        if: always()
        working-directory: s8
        run: docker compose down -v