name: Run test  - S8

on:
  push: 
    branches:
      - main

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd s8 && npm install

     
      - name: Charge .env file
        run: |
          cd s8
          echo DB_HOST="db" >> .env
          echo DB_PORT="5432" >> .env
          echo DB_USER="postgres" >> .env
          echo DB_PASSWORD="postgres" >> .env
          echo DB="postgres" >> .env
        
      - name: Initialize DB
        run: cd s8 && docker compose up -d


      - name: Run Migration
        run: cd s8 && npx knex migrate:latest

      - name: Generate Migration
        run: cd s8 && npx knex generate:migration
        
      - name: Run tests
        run: cd s8 && npm run test /test/*.spec.ts