name: Run unit tests

on:
  push:
    branches: [main]
    paths:
      - 's8/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
      

      - name: Install dependencies
  
        run: npm ci --prefix **/

      - name: Run tests

        run: npm test -- test/**/*.spec.ts --prefix **/ 